# Copyright (c) 2025, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Create the gateway server configuration file
  ansible.builtin.template:
    src: "server.conf.j2"
    dest: "{{ gateway_server_config_dir }}/gateway.conf"
    mode: "0600"
    owner: "{{ gateway_server_user }}"
    group: "{{ gateway_server_group }}"
    lstrip_blocks: true
    backup: true
  when: gateway_application_mode == 'server'

- name: Create the gateway runner configuration file
  ansible.builtin.template:
    src: "runner.conf.j2"
    dest: "{{ gateway_server_config_dir }}/gateway.conf"
    mode: "0600"
    owner: "{{ gateway_server_user }}"
    group: "{{ gateway_server_group }}"
    lstrip_blocks: true
    backup: true
  when: gateway_application_mode == 'runner'

- name: Create the gateway systemd file
  ansible.builtin.template:
    src: iagctl.service.j2
    dest: /usr/lib/systemd/system/iagctl.service
    owner: root
    group: root
    mode: "0644"

- name: Create the gateway systemd environment file
  ansible.builtin.template:
    src: iagctl.env.j2
    dest: "{{ gateway_server_service_env_file }}"
    mode: "0600"
    owner: "{{ gateway_server_user }}"
    group: "{{ gateway_server_group }}"
    lstrip_blocks: true
    backup: true
  when: >-
    gateway_server_store_backend == 'dynamodb' or
    gateway_server_environment | length > 0 or
    gateway_server_connect_proxy_enabled | bool

- name: Create the gateway encryption key file
  ansible.builtin.copy:
    content: "{{ gateway_secrets_encrypt_key }}"
    dest: "{{ gateway_secrets_encrypt_key_file }}"
    mode: "0600"
    owner: "{{ gateway_server_user }}"
    group: "{{ gateway_server_group }}"

- name: Deploy logrotate config for Gateway
  ansible.builtin.template:
    src: iagctl.logrotate.j2
    dest: /etc/logrotate.d/iagctl
    owner: root
    group: root
    mode: "0644"
